In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 3s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.19427723, -0.57595146, -0.06506663, -0.5722861 ,  0.5529149 ,
        -0.11350089, -0.13387021, -0.26006287, -1.0342588 ,  0.16237082]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.13365464, 0.06186969, 0.10312226, 0.06209689, 0.19131033,
        0.09824664, 0.09626567, 0.0848529 , 0.03912349, 0.1294575 ]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3202744

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
  79/1875 [>.............................] - ETA: 1s - loss: 1.0663 - accuracy: 0.6994  

2022-07-09 23:26:12.400310: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1875/1875 [==============================] - 1s 609us/step - loss: 0.2999 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 1s 601us/step - loss: 0.1450 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 1s 599us/step - loss: 0.1083 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 1s 601us/step - loss: 0.0876 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 1s 601us/step - loss: 0.0777 - accuracy: 0.9753


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0746 - accuracy: 0.9767 - 161ms/epoch - 514us/step


[0.07464351505041122, 0.9767000079154968]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.34131302e-08, 1.45986343e-08, 3.13625856e-06, 1.95981876e-04,
        8.77239253e-11, 7.05293189e-07, 1.27375188e-13, 9.99778330e-01,
        7.86114924e-08, 2.18286568e-05],
       [3.00642391e-08, 3.34189713e-06, 9.99974847e-01, 1.38967262e-05,
        1.78689037e-14, 3.75717354e-06, 1.19290611e-09, 4.74243684e-14,
        4.00072668e-06, 3.80740985e-13],
       [6.54341576e-08, 9.98922527e-01, 1.54175126e-04, 2.36433084e-06,
        1.87822239e-04, 5.45647993e-07, 1.63917878e-06, 6.26386493e-04,
        1.02898470e-04, 1.40755276e-06],
       [9.99934912e-01, 7.71693598e-10, 3.82228927e-06, 1.05182586e-07,
        3.74178541e-07, 7.18743513e-06, 6.32770661e-06, 4.11522842e-06,
        1.26227944e-08, 4.31802109e-05],
       [4.54943120e-06, 2.29015570e-10, 5.12581835e-07, 7.03729057e-08,
        9.98989761e-01, 1.49146422e-06, 5.63830099e-06, 3.85936073e-05,
        3.63722006e-06, 9.55705764e-04]], dtype=float32)>