In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [4]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )
        
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [5]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [6]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(y_pred)

tensor([4])


In [7]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [8]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [9]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [11]:
print('Before ReLU')
print(hidden1)
hidden1 = nn.ReLU()(hidden1)
print('After ReLU')
print(hidden1)

Before ReLU
tensor([[0.0000, 0.1162, 0.0000, 0.0000, 0.4347, 0.0000, 0.3176, 0.4540, 0.2190,
         0.0000, 0.2596, 0.0000, 0.0953, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0237, 0.0545, 0.2993, 0.2970, 0.0240, 0.3675, 0.6698, 0.0000,
         0.0000, 0.3911, 0.0000, 0.3799, 0.0000, 0.0000, 0.0000, 0.0000, 0.2924,
         0.0059, 0.0000],
        [0.0000, 0.3763, 0.0690, 0.0000, 0.0025, 0.0723, 0.3793, 0.4816, 0.0000,
         0.0000, 0.2668, 0.0000, 0.2711, 0.0000, 0.0000, 0.0000, 0.0000, 0.0360,
         0.0000, 0.0946]], grad_fn=<ReluBackward0>)
After ReLU
tensor([[0.0000, 0.1162, 0.0000, 0.0000, 0.4347, 0.0000, 0.3176, 0.4540, 0.2190,
         0.0000, 0.2596, 0.0000, 0.0953, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0237, 0.0545, 0.2993, 0.2970, 0.0240, 0.3675, 0.6698, 0.0000,
         0.0000, 0.3911, 0.0000, 0.3799, 0.0000, 0.0000, 0.0000, 0.0000, 0.2924,
         0.0059, 0.0000],
        [0.

In [12]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)

In [13]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [16]:
print(logits.sum(axis=1))
print(pred_probab.sum(axis=1))

tensor([0.5327, 0.3482, 0.2960], grad_fn=<SumBackward1>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [20]:
for name, param in model.named_parameters():
    print(name)
    print(param.size())
    print(param[:2])
    print('-' * 20)

linear_relu_stack.0.weight
torch.Size([512, 784])
tensor([[ 0.0200, -0.0305,  0.0089,  ...,  0.0304, -0.0170,  0.0225],
        [-0.0159, -0.0151, -0.0259,  ..., -0.0289,  0.0086,  0.0014]],
       grad_fn=<SliceBackward0>)
--------------------
linear_relu_stack.0.bias
torch.Size([512])
tensor([-0.0351,  0.0067], grad_fn=<SliceBackward0>)
--------------------
linear_relu_stack.2.weight
torch.Size([512, 512])
tensor([[ 0.0038,  0.0019,  0.0035,  ...,  0.0168, -0.0417,  0.0226],
        [ 0.0124,  0.0315,  0.0306,  ...,  0.0213,  0.0362, -0.0399]],
       grad_fn=<SliceBackward0>)
--------------------
linear_relu_stack.2.bias
torch.Size([512])
tensor([-0.0348,  0.0051], grad_fn=<SliceBackward0>)
--------------------
linear_relu_stack.4.weight
torch.Size([10, 512])
tensor([[-0.0071, -0.0158, -0.0189,  ...,  0.0038, -0.0341,  0.0154],
        [-0.0125,  0.0253,  0.0297,  ...,  0.0078, -0.0159, -0.0392]],
       grad_fn=<SliceBackward0>)
--------------------
linear_relu_stack.4.bias
torch.S